// Environment variables (Replace with actual values)
const endpoint = "https://iocl-hr-openai-service.openai.azure.com/";
const deployment = "gpt-4o";
const subscriptionKey = "9f82a1e82c7444e8a8453f9d7f787e2a"; // Your actual API key

// Function to call the chatbot API with consistent settings from Azure OpenAI Studio
async function callChatbotAPI(message) {
    const url = `${endpoint}/openai/deployments/${deployment}/chat/completions?api-version=2024-02-15-preview`; // Updated API version as seen in the screenshot

    // Prepare the headers and body based on the Azure OpenAI Studio configuration
    const headers = {
        "Content-Type": "application/json",
        "api-key": subscriptionKey
    };

    // Payload as shown in the Azure OpenAI configuration
    const body = {
        "messages": [
            { 
                "role": "system", 
                "content": "You are an AI assistant that helps people find information." 
            },
            { 
                "role": "user", 
                "content": message 
            }
        ],
        "max_tokens": 800,  // Match the max tokens as shown
        "temperature": 0.7, // Match the temperature setting
        "top_p": 0.95,      // Match the top_p setting
        "frequency_penalty": 0,
        "presence_penalty": 0
    };

    try {
        // Fetch response from the Azure OpenAI endpoint
        const response = await fetch(url, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(body)
        });

        if (response.ok) {
            const jsonResponse = await response.json();
            console.log("Received response:", jsonResponse);
            return jsonResponse.choices[0].message.content; // Extracting the message content
        } else {
            console.error('Error response from API:', response.status, response.statusText);
            return 'Error retrieving a response. Please try again later.';
        }
    } catch (error) {
        console.error('Fetch error:', error);
        return 'Error retrieving a response. Please check your connection and try again later.';
    }
}

// Function to send the message and handle response, including PDF checks
async function sendMessage() {
    const inputField = document.getElementById('chat-input');
    const message = inputField.value.trim();

    if (message === '') return;

    addMessageToChat('You', message);
    inputField.value = '';

    const chatbotResponse = await callChatbotAPI(message);
    let responseWithLink = chatbotResponse;

    // Check if the response includes information indicating it's from a PDF
    if (chatbotResponse.toLowerCase().includes('pdf') || message.toLowerCase().includes('transfer allowance')) {
        responseWithLink += `<br><a href="https://ioclhhrchatgpt.blob.core.windows.net/documents/hrhbtb.pdf" target="_blank" style="color: blue; text-decoration: underline;">View in PDF</a>`;
    } else {
        responseWithLink += `<br><small style="color: grey;">It was generated by AI.</small>`;
    }

    addMessageToChat('IOCL Bot', responseWithLink);
}

// Function to add a message to the chat window
function addMessageToChat(sender, message) {
    const messagesContainer = document.getElementById('chatbot-messages');
    const messageElement = document.createElement('div');
    messageElement.innerHTML = `${sender}: ${message}`;
    messagesContainer.appendChild(messageElement);
    messagesContainer.scrollTop = messagesContainer.scrollHeight;
}

// Function to toggle the chatbot window
function toggleChatbot() {
    const chatbotWindow = document.getElementById('chatbot-window');
    if (chatbotWindow.classList.contains('active')) {
        chatbotWindow.classList.remove('active');
        chatbotWindow.style.animation = 'fadeOut 0.3s ease-out';
        setTimeout(() => {
            chatbotWindow.style.display = 'none';
        }, 300);
    } else {
        chatbotWindow.style.display = 'flex';
        chatbotWindow.classList.add('active');
        chatbotWindow.style.animation = 'fadeIn 0.3s ease-out';
        addMessageToChat('IOCL Bot', 'Hello, how may I assist you?');
    }
}
